---
- name: Configure API Host
  hosts: all
  vars:
    mule_home: /opt/mule-enterprise-standalone-4.4.0
  environment:
    MULE_HOME: '{{ mule_home }}'
  tasks:
    - name: Install OpenJDK 1.8
      yum:
        name: java-1.8.0-openjdk
        state: present
        update_cache: yes

    - name: Install MySQL client
      yum:
        name: mysql
        state: latest
        update_cache: yes
    
    - name: Download and extract Mule Enterprise Standalone
      ansible.builtin.unarchive:
        src: https://s3.amazonaws.com/new-mule-artifacts/mule-ee-distribution-standalone-4.4.0.zip
        dest: /opt
        remote_src: yes

    - name: Set MULE_HOME environment variable
      delegate_to: localhost
      copy:
        content: export MULE_HOME="/opt/mule-enterprise-standalone-4.4.0"
        dest: /etc/profile.d/mule_home.sh
  
    - name: Install Mule Daemon
      ansible.builtin.shell: "{{ mule_home }}/bin/mule install"

    - name: Start Mule Daemon
      ansible.builtin.shell: "{{ mule_home }}/bin/mule start"

    - name: Register runtime with Anypoint Platform
      ansible.builtin.shell: "{{ mule_home }}/bin/amc_setup -H d3dd1acb-c2d9-4a7d-8202-587a8a8d8867---657980 api-host"

    - name: Get the SQL DB script from GitHub repo
      get_url: 
        url: https://raw.githubusercontent.com/gonzalo-camino/fssm-inventory-api/main/src/main/resources/db/script.sql
        dest: /tmp

    # - name: Execute SQL script to populate DB
    #   community.mysql.mysql_db:
    #     login_host: 
    #     state: import
    #     name: all
    #     target: /tmp/script.sql
